[workspace]
resolver = "2"
members = [
  "vss",
  "vss-desktop",
  "vss-android",
  "vss-catalog",
  "vss-openxr",
  "vss-web",
  "vss-winit"
]

[workspace.dependencies]
ash = "0.38"
cgmath = "0.18"
raw-window-handle = "0.6"
rust-i18n = "4"
wgpu = "29"
wgpu-hal = "29"
winit = "0.30"

[profile.profile]
inherits = "release"
debug = true
