[package]
name = "vss-desktop"
edition = "2018"
version = "1.0.0"
authors = ["The Visual System Simulator Developers"]
license = "Apache-2.0"

[dependencies]
vss = { path = "../vss" }
clap = "2"
serde_json = "*"
av = { git = "https://github.com/unpatched/rust-av.git", branch = "master", optional = true }

[features]
default = []
video = ["av"]
