[package]
name = "vss-desktop"
edition = "2018"
version = "1.0.0"
authors = ["The Visual System Simulator Developers"]
license = "Apache-2.0"
[dependencies]
wgpu = { workspace = true }
vss = { path = "../vss" }
vss-winit = { path = "../vss-winit" }
vss-openxr = { path = "../vss-openxr" }
pollster = "0.4"
clap = { version = "4", features = ["derive"] }
glob = "0.3"
ac_ffmpeg = { package = "ac-ffmpeg", version = "0.19.0", optional = true }
rfd = "0.15"
tempfile = "3"

[features]
default = []
video = ["ac_ffmpeg"]
