[package]
name = "vss"
edition = "2018"
version = "1.0.0"
authors = ["The Visual System Simulator Developers"]
license = "Apache-2.0"

[dependencies]
serde_json = "1"
gfx_core = "0.9"
gfx_device_gl = "0.16"
gfx_window_glutin = "0.31"
gfx = "0.18"
gfx_gl = "0.6"
glutin = "0.21"
ws = "0.9"
image = "0.23"
