[package]
name = "vss"
edition = "2018"
version = "1.0.0"
authors = ["The Visual System Simulator Developers"]
license = "Apache-2.0"

[dependencies]
serde_json = "1"
gfx_core = "0.8"
gfx_device_gl = "0.15"
gfx_window_glutin = "0.28"
gfx = "0.17"
gfx_gl = "0.5"
glutin = "0.19"
ws = "0.7"
image = "0.21"
