[package]
name = "vss"
version = "1.0.0"
edition = "2021"
authors = ["The Visual System Simulator Developers"]
license = "Apache-2.0"
resolver = "2"

[dependencies]
cgmath = { workspace = true }
raw-window-handle = { workspace = true }
wgpu = { workspace = true }
image = "0.25"
bitflags = "2.13"
futures-intrusive = "0.5"
instant = "0.1"
pollster = "0.4"

[target.'cfg(target_os = "android")'.dependencies]
ash = { workspace = true }
wgpu-hal = { workspace = true }

[features]
webgl = ["wgpu/webgl"]
