[package]
name = "vss-openxr"
edition = "2018"
version = "0.1.0"
authors = ["The Visual System Simulator Developers"]
license = "Apache-2.0"

[dependencies]
ash = "0.38"
cgmath = { workspace = true }
openxr = { git = "https://github.com/schulzch/openxrs", branch = "metal", features = ["static"] }
pollster = "0.4"
vss = { path = "../vss" }
wgpu = { workspace = true }
wgpu-hal = { workspace = true, features = ["vulkan"] }

[target.'cfg(target_vendor = "apple")'.dependencies]
objc2 = "0.6.4"
objc2-metal = { version = "0.3.2", default-features = false, features = [
  "std",
  "MTLAllocation",
  "MTLCommandBuffer",
  "MTLCommandEncoder",
  "MTLCommandQueue",
  "MTLDevice",
  "MTLPixelFormat",
  "MTLRenderCommandEncoder",
  "MTLRenderPass",
  "MTLResource",
  "MTLTexture",
] }
